---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dstack-app
  template:
    metadata:
      labels:
        app: dstack-app
    spec:
      containers:
      - name: dstack-app
        image: dstack-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dstack-app-service
spec:
  type: NodePort
  selector:
    app: dstack-app
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dstack-guest-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dstack-guest-services
  template:
    metadata:
      labels:
        app: dstack-guest-services
    spec:
      containers:
      - name: dstack-guest-services
        image: dstack-guest-sim:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: dstack-tee-services
spec:
  type: NodePort
  selector:
    app: dstack-guest-services
  ports:
  - port: 5001
    targetPort: 5001
